gouravthakur39/beginners-C-program-examples

- Dice.c
> Adjustable dice roller program

- SwapByRefandCopy.c
A Simple C Program to show the difference between Swapping by Reference and Swapping by Copy
> Swap By Reference VS Swap By Copy

- ArmstrongNumber.c
- Largest.c
Added a program to check whether a given number is Armstrong or not
> Armstrong Numbers

- SquareRoot.c
> Program to find the square root of a number

- combine_calculator.c
Add some basic codes using C language #3 
Using switch case to combine some codes
> Add some basic codes using C language

- DecimalToHexadecimalViceVersa.c
This is a C program file to convert decimal to hexadecimal number vice versa.
> new C program added

- Prime.c
Because we can use 11 as an example: 11 squared is roughly 3 (c programs automatically throw the decimal if a variable is under “int”).
> Changed to number squared % j

- BackgroundThreadSorter.c
This program demonstrates the usage of pthreads, mutexes and qsort(an inbuilt C sorting function).
This programs implements a background thread which sorts a fixed size
array of structures every 10 seconds and displays the array.
The main thread can input elements to write into the fixed size array.
A mutex is used to serialize the array from the main thread and
background thread. An array of structures is used to demonstrate the
usage of a comparator in qsort.
> Add program which implements a background thread sorter

- FibonacciGeneration.c
Simple Recursive Nth Fibonacci Number Generator. Beginner Friendly with appropriate Indentation and Comments.
> Nth Fibonacci Number Generator

- CommonElementsInTwoArrays.c
Algorithm that compares elements between 2 arrays of length and variable values
> CommonElementsInTwoArrays.c

- CelciusToKelvinConv.c
So, I was looking through Hacktoberfest repositories-- I randomly came across this one, but I only found one weather converter, so I decided to write another one!
And that's my life story.
> Added Celcius to Fahrenheit converter. (for fun)

- NestedIfLeapYear.c
Earlier program is not well written. Beginners will find problems while running it.
> ReEdit NestedIfLeaptest: Fix Minor Bugs

- AllTempScalesConv.c
Same life story as @alwayslivid, but when I saw his code I decided to do a complete conversor, with all the 3 main temperature scales (Celsius, Kelvin and Fahrenheit). I hope my code can help others about functions and switch-case method.
> Added all temperature scales conversor

- SparseMatrix_017.c
> SparseMatrix_017.cpp

- lcm.c
Calculates the least common multiple of two numbers using the Euclidean Algorithm.
> Add lcm calculator

- last-digit-fibonacci.c
Computes the last digit for the Fibonacci number of a given index. 
For example, if the given input is 200, the 200th term in the Fibonacci series is 28057117299251014003761193241303867718952**5**. The output is the last digit of this number which is 5
> add calculator for last digit of nth fibonacci number

- Even Fibonacci numbers
A program that prompts the user to input the range up to which they want to display the even Fibonacci number and finds it's sum.
> Even Fibonacci Number

- Automorphic_number.c
An Automorphic number is a number whose square ends with the same digits as the original number. E.g – 5, 6, 76 etc.
> Automorphic Number

- PascalTriangle.c
I have added a file to show a pattern of pascal triangle by using some binomial formula to convert every number in a row.
> added a pattern for pascal triangle

- counting_sort.c
Sorts the input array by counting the occurrences of each number from 0 to a max value (also given as input). More info at: https://www.interviewcake.com/concept/java/counting-sort
> Add counting sort

- README.md
- SelectionSort.c
A program for sorting a given array using Selection sort algorithm
> Added SelectionSort.c

- large_factorial.c
My code can calculate factorial upto 5000! , that is such a huge value that we can not store in any built in data type. Please let me contribute my this code to your collection.
> added code to calculate upto 5000!

- dynamicMemoryAllocation.c
hello, i think it can be helpful for newbie whose want to use malloc
> add an example of malloc()

- increment_number.c
Added:
- increment_number.c
- What goes on in this Program is that we have an Integer('num') with the Value of 0. Then there is another Integer('increment')
with a Value of 1. We then have a While-Loop that says: "While num is less than 100, use the Integer, 'increment' to increment
the Value of num by 1 every second".
> Added New File: increment_number.c

- Star_Pattern.c
Prints the basic star pattern increasing in number going top to down.
> Prints Basic Star Pattern

- Pattern Combos
- Pattern1.c
- Position of First'n'Second maximum element in Array without sorting
- Position_of_First'n'Second_max_elements_without_sorting_array
Step wise guide for beginners to gather a quick reflex on Pattern Questions. More are to yet to be added on.
> Pattern Questions for beginners.

- Addition.c
Modified Addition.c
added "The sum is" in addition.c
> Modified Addition.c

- README.md
- priority_queue.c
I have implemented a priority queue program, which takes the program ID and priority value as inputs, and stores them in a Max-Heap, for efficient querying, in the program. I have implemented this program in the C Programming Language.
In my program, the greater the priority value of the task, the higher is the priority of the task.
> Implementation of Priority Queue using Max Heap Using C

- TemperatureSwitch.c
Made a program for celsius to fahrenheit and vice versa conversion.
> Added a program for temperature switch using c algorithm

- SumUsingThreads.c
I have updated my code as you said
> Updated Code

- omang_fibonacci.c
User is asked for number of elements of the Fibonacci to be printed and Fibonacci is printed up to that number elements
> Fibonnaci Series

- volume_cone_sphere.c
>  calculate and print the volume and surface area of ​​a straight cone, a cylinder, or a sphere

- NaiveModularInverse.c
- fastModuloExponentiation.c
Using a naive approach to calculate modular inverse of small numbers. 
Time complexity is O(m), m is the modulo integer.
> Added prorgam to Calculate Modular Inverse

- Number_to_Character.c
- README.md
Added Number_to_Character Program. This program have a number input and return the character of each digit of this number. Besides that, the session of links for the programs has been updated to present the program added.
> Added Number_to_Character Program

- Convert an array to reduced form.c
- kth smallest no in an array.c
To print the kth smallest no in an array.c
> kth smallest no in an array.c

- Adding_Fractions.c
Sorry for some small indentation with 1-2 tabs it looked ok on bash :(
> Adding fractions algorithm

- ip_address.c
This C program helps you to find which type of IP address it is.
> Created ip_address.c

- Log_Conversion.c
I've Added Logarithm Conversion. Kindly review and merge it into your master branch.
> Log_conversion

- README.md
- lambda_in_c.c
Hi, I add a lambda example by using gcc and clang extension syntax
> add lambda examples by compiler extension

- to find average & sum of a,b,c in one function
you can learn how to find sum and average in one program.
>  to find average & sum of a,b,c in one function

- check functon is even or odd in c programming
simple program for learning c language
> check functon is even or odd in c programming

- Address of 1-D array
Corrected the code to return address of each element of array and with the help of printf statement and comments made the code more descriptive.
> Update Address of 1-D array

- CalculateSimpleInterest.c
Asking user the input for Principle Amount, Number of years, Rate of Interest and then calculating Simple Interest
> Added CalculateSimpleInterest.c

- Slicestring
Writing a function slice() to slice a string. It will change the original string such that it is now the sliced strings. Taking m and n as the start and ending position for slice.
> Slicestring

- simple_interest.c
A basic beginner friendly program to calculate simple interest.
> Calculate Simple Interest

- finding the first missing natural number
Enter the squence of natural numbers. The very first missing natural number will be resulted by this program. If no number is missing then the very next natural number in the continuing sequence will be calculated.
> Finding the first missing natural number
